### ISSUE TITLE
Do we tend towards a jurisprudential or towards a theological topic?

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#25]
Franzi kept talking about the thing that relates to apologetics where the theory is that if something is absurd you must use more words on explaining it to your parishers. And if its more natural, less words suffice.

There's definitely something to that thought. For example it might be interesting to see how much was written on the صورة الإجلاص given how much simpler the basic concept of توحيد is than the concept of trinity, which has volumes upon volumes of exegesis written on it. Just an example though as it would be too much for us to get into comparative theology.

What she also kept bringing up was the question of whether we wish to concern ourselves with theological topics or whether jurisprudential ones wouldn't be better.

**Comment by FranziskaBlunck** [comment]
"Franzi kept talking about the thing that relates to apologetics where the
theory is that if something is absurd you must use more words on explaining
it to your parishers. And if its more natural, less words suffice."

Well, yes, but it is not because it is absurd but because the listener or
reader of the Tafaseer needs to really understand the underlying message in
the Ayah. Rationalists, Orthodox and Apologetic writers are certainly
people who like to beat around the bush.

Three people that might prove this theory:

Abu bekr al-9amm (الصم)
- he wrote 120 traits alone about the Bismillah

Ubeidallah b muhammad b Jirw
- large Tafaseer compendium

Muhammad b Bahr Abu Muslim
- the length of his exegetical seems to be phenomenally

They do not appear in our corpus, i just wanted to mention them and their
outstanding amount of words (and you could probably really use word absurd
here ;) )

It is indeed mentioned (by Goldziher) that in this case rationalists/or
just doctrinal/ dogmatical thinkers are pretty "mujtaheed" writing and
never stop doing so. But getting statistics for that and even make a sweet
little formula out of it (in which way this could work, i don't really know
xD)

One little exception for rationalists (mu3tazili) is when they really go
deep into linguistical explanations which is where a big output of words
might be fine.
